# Generated by Django 6.0 on 2025-12-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('placement', models.CharField(choices=[('home_1', 'Home 1'), ('home_2', 'Home 2'), ('home_3', 'Home 3'), ('home_4', 'Home 4'), ('popup', 'Popup')], max_length=20)),
                ('desktop_image', models.ImageField(blank=True, null=True, upload_to='advertisements/desktop/')),
                ('desktop_image_url', models.URLField(blank=True, null=True)),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='advertisements/mobile/')),
                ('redirect_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
