# Generated by Django 5.1.5 on 2026-01-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='preparing_for',
        ),
        migrations.AddField(
            model_name='user',
            name='preparing_for',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.preparation'),
        ),
    ]
