# Generated by Django 5.1.5 on 2026-01-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preparing_for',
            field=models.JSONField(blank=True, default=list, help_text='List of programs user is preparing for', null=True),
        ),
    ]
