# Generated by Django 5.1.5 on 2026-03-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_preparation_remove_user_preparing_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preparing_for',
        ),
        migrations.DeleteModel(
            name='Preparation',
        ),
        migrations.AddField(
            model_name='user',
            name='preparing_for',
            field=models.CharField(blank=True, choices=[('CSIT', 'BSc CSIT'), ('BIT', 'BIT'), ('BCA', 'BCA'), ('CMAT', 'CMAT')], max_length=10, null=True),
        ),
    ]
