# Generated by Django 5.1.5 on 2026-01-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mocktest',
            options={'ordering': ['priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='mocktest',
            name='is_old_question',
            field=models.BooleanField(default=False, help_text='Mark if this mock test is based on old questions'),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Lower number = higher priority in list view'),
        ),
    ]
