# Generated by Django 5.1.5 on 2026-01-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(help_text='Supports LaTeX and Rich Text'),
        ),
    ]
