# Generated by Django 5.1.5 on 2026-01-19 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0002_alter_program_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('university', models.CharField(help_text='University name (text-based for flexibility)', max_length=255)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='classes/featured/')),
                ('featured_image_url', models.URLField(blank=True, help_text='Use if image is hosted externally', null=True)),
                ('is_online_available', models.BooleanField(default=False)),
                ('online_original_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('online_discounted_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('online_location', models.CharField(blank=True, help_text='Zoom, Google Meet, Microsoft Teams, etc.', max_length=255)),
                ('is_physical_available', models.BooleanField(default=False)),
                ('physical_original_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('physical_discounted_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('physical_location', models.CharField(blank=True, help_text='Location where physical classes will run', max_length=255)),
                ('top_description', models.TextField(help_text='Rich text content (CKEditor/TinyMCE)')),
                ('bottom_description', models.TextField(blank=True, help_text='Additional rich text content')),
                ('entrance_book_link', models.URLField(blank=True)),
                ('entrance_syllabus_link', models.URLField(blank=True)),
                ('mock_test_link', models.URLField(blank=True, help_text='Mock test & practice questions link')),
                ('entrance_exam_update_link', models.URLField(blank=True)),
                ('highlights', models.TextField(blank=True, help_text='Key highlights / bullet points (optional)')),
                ('duration', models.CharField(blank=True, help_text='e.g. 3 Months, 6 Weeks', max_length=100)),
                ('batch_start_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Lower number = higher priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='programs.program')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
