# Generated by Django 5.1.5 on 2026-01-28 10:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='bottom_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Additional rich text content'),
        ),
        migrations.AlterField(
            model_name='class',
            name='highlights',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Key highlights / bullet points (rich text)'),
        ),
        migrations.AlterField(
            model_name='class',
            name='meta_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='SEO description (rich text)'),
        ),
        migrations.AlterField(
            model_name='class',
            name='top_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Main rich text content (CKEditor)'),
        ),
    ]
