# Generated by Django 6.0 on 2025-12-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('institute_name', models.CharField(max_length=255)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='exam/covers/')),
                ('top_description', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('form_fee', models.CharField(blank=True, max_length=50)),
                ('double_fee', models.CharField(blank=True, max_length=50)),
                ('opens_at', models.DateField()),
                ('closes_at', models.DateField()),
                ('full_mark', models.CharField(blank=True, max_length=50)),
                ('pass_mark', models.CharField(blank=True, max_length=50)),
                ('question_type', models.CharField(blank=True, max_length=100)),
                ('number_of_questions', models.PositiveIntegerField()),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('negative_marking', models.CharField(blank=True, max_length=100)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-opens_at'],
            },
        ),
    ]
