# Generated by Django 6.0 on 2025-12-20 06:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='meta_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='top_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
