# Generated by Django 5.1.5 on 2026-01-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='brand',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='College Info Nepal', help_text='Author name(s)', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='book',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, help_text='e.g. First Edition', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary for SEO / preview'),
        ),
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('paperback', 'Paperback'), ('hardcover', 'Hardcover'), ('ebook', 'eBook'), ('audiobook', 'Audiobook')], default='paperback', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, help_text='Genre or category (e.g. Fiction, Business)', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='in_stock',
            field=models.BooleanField(default=True, help_text='Is the book currently available?'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='College Info Nepal', help_text='Publisher / Brand', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='sku',
            field=models.CharField(blank=True, help_text='Internal or vendor SKU', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle', max_length=255),
        ),
        migrations.AddField(
            model_name='bookimage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Main product image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Book price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='SEO-friendly alt text', max_length=255),
        ),
    ]
