# Generated by Django 5.1.5 on 2026-01-19 05:27

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_brand_book_author_book_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Full book description (supports formatting)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='excerpt',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Short summary for SEO / preview'),
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=255)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5')),
                ('review_text', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Uncheck to hide review from public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='book.book')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
