# Generated by Django 6.0 on 2025-12-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bottom_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/featured/'),
        ),
        migrations.AddField(
            model_name='course',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='top_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.URLField(blank=True, help_text='External detail page link'),
        ),
    ]
