# Generated by Django 5.1.5 on 2026-01-16 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0002_alter_program_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='syllabus/')),
                ('featured_image_url', models.URLField(blank=True, null=True)),
                ('university', models.CharField(max_length=255)),
                ('total_questions', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField()),
                ('pass_marks', models.PositiveIntegerField()),
                ('negative_marking', models.BooleanField(default=False)),
                ('negative_mark_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('question_type', models.CharField(help_text='MCQ, Subjective, Mixed etc.', max_length=255)),
                ('exam_duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('top_description', models.TextField(blank=True)),
                ('main_description', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='programs.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('marks', models.PositiveIntegerField()),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='syllabus.syllabus')),
            ],
            options={
                'unique_together': {('syllabus', 'subject_name')},
            },
        ),
    ]
