# Generated by Django 5.1.5 on 2026-01-19 05:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='main_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='top_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
