# Generated by Django 6.0 on 2025-12-20 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_course_bottom_description_course_featured_image_and_more'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('priority', models.PositiveIntegerField(default=999)),
                ('cover', models.URLField(blank=True, help_text='Cover image URL')),
                ('logo', models.URLField(blank=True, help_text='Logo image URL')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('external_link', models.URLField(blank=True, help_text='External detail page link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colleges', to='course.course')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colleges', to='university.university')),
            ],
            options={
                'ordering': ['priority', 'title'],
            },
        ),
    ]
