# Generated by Django 6.0 on 2025-12-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('course', '0002_course_bottom_description_course_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='course',
        ),
        migrations.AddField(
            model_name='college',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='colleges', to='course.course'),
        ),
    ]
