# Generated by Django 6.0 on 2025-12-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_remove_college_course_college_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified by College Info Nepal'),
        ),
        migrations.AlterField(
            model_name='college',
            name='cover',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.URLField(blank=True),
        ),
    ]
